server:
  port: 8093
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
eureka:
  instance:
  prefer-ip-address: true
  client:
      fetch-registry: true
      register-with-eureka: true


